const BRAND = "#14457B";
const CARD = "#E7ECF4";

function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return (
    <section id={id} className="scroll-mt-6 rounded-lg border p-5" style={{ borderColor: BRAND }}>
      <h2 className="text-base font-bold mb-2" style={{ color: BRAND }}>{title}</h2>
      <div className="text-sm text-slate-700 space-y-2">{children}</div>
    </section>
  );
}

export default function LegalPage() {
  return (
    <div className="space-y-6">
      <section className="rounded-lg overflow-hidden">
        <div className="px-6 py-5" style={{ backgroundColor: BRAND }}>
          <h1 className="text-xl font-bold text-white">Legal &amp; Disclaimers</h1>
          <p className="mt-1 text-sm text-white/85">
            The compliance notices that apply to every tool in ProEdCS Coder AI. This page stays available at all times — it is not a one-time notice to dismiss.
          </p>
        </div>
      </section>

      {/* Quick nav to each section */}
      <div className="rounded-lg border p-3 flex flex-wrap gap-3 text-xs" style={{ borderColor: BRAND, backgroundColor: CARD }}>
        {[
          ["general", "General / Educational Use"],
          ["ai-output", "AI-Generated Content"],
          ["phi", "PHI & Patient Data"],
          ["icd10", "ICD-10 Content"],
          ["hcpcs", "HCPCS Content"],
          ["cpt", "CPT / AMA Content"],
          ["hedis", "HEDIS / Quality Measures"],
          ["hipaa", "HIPAA & Data Handling"],
        ].map(([id, label]) => (
          <a key={id} href={`#${id}`} className="hover:underline" style={{ color: BRAND }}>
            {label}
          </a>
        ))}
      </div>

      <Section id="general" title="General / Educational Use">
        <p>
          ProEdCS Coder AI is an internal tool built for ProEd Consulting &amp; Staffing&apos;s coding, CDI, and auditing staff. All content generated by this application — code suggestions, query drafts, policy documents, claim validation findings, and complexity estimates — is provided for educational and workflow-support purposes only.
        </p>
        <p>
          Nothing in this application constitutes legal advice, coding certification, or a guarantee of claim acceptance. Every output should be independently reviewed by a qualified coder or compliance professional before being relied upon for billing, documentation, or submission to a payer.
        </p>
      </Section>

      <Section id="ai-output" title="AI-Generated Content">
        <p>
          Several tools in this application (Codes Search, Policies Q&amp;A, Query Forms, Code Documentation Check, Claim Validation, Policy Document Generator) use an AI language model to produce their output. AI-generated content may contain errors, omissions, or outdated information, and should never be treated as authoritative on its own.
        </p>
        <p>
          Always verify AI-generated suggestions against current CMS, payer, and organizational guidance before acting on them. ProEd and AXCEL make no guarantee of accuracy, completeness, or fitness for a particular billing or clinical outcome.
        </p>
      </Section>

      <Section id="phi" title="PHI &amp; Patient Data">
        <p>
          Do not enter real patient names, dates of birth, medical record numbers, Social Security numbers, or any other individually identifiable information into any text field in this application. Use de-identified scenarios, placeholder values, or generic descriptions instead.
        </p>
        <p>
          This applies across every tool that accepts free-text input, including Query Forms, Code Documentation Check, Claim Validation, and Policy Document Generator.
        </p>
      </Section>

      <Section id="icd10" title="ICD-10 Content">
        <p>
          ICD-10-CM diagnosis codes, their descriptions, and the official coding instructions (Includes, Excludes1, Excludes2, Use Additional Code, Code First) are published by the Centers for Disease Control and Prevention (CDC) and the Centers for Medicare &amp; Medicaid Services (CMS) as public domain content. No license is required to view, search, or reference this content.
        </p>
      </Section>

      <Section id="hcpcs" title="HCPCS Content">
        <p>
          HCPCS Level II codes (used for durable medical equipment, supplies, and certain services) are published by CMS as public domain content. Like ICD-10-CM, no license is required to use this content.
        </p>
      </Section>

      <Section id="cpt" title="CPT / AMA Content">
        <p>
          CPT is a registered trademark of the American Medical Association. Copyright American Medical Association. All rights reserved. CPT codes, descriptions, and the official Evaluation &amp; Management (E/M) coding guidance are copyrighted content requiring a license from the AMA to display, distribute, or embed in a software product.
        </p>
        <p>
          Tools in this application that relate to CPT-coded services (the E/M Level Helper, CPT mode in Code Documentation Check, and the CPT-specific portions of Claim Validation) operate in placeholder mode: they display only general complexity levels or service categories, and never a specific CPT code number, pending an active AMA license held by ProEd. This applies regardless of how a request to display such content is framed.
        </p>
      </Section>

      <Section id="hedis" title="HEDIS / Quality Measures">
        <p>
          HEDIS is a registered trademark of the National Committee for Quality Assurance (NCQA). The measure specifications referenced in this application are used for coding and documentation-support purposes and do not constitute an NCQA-certified HEDIS reporting product.
        </p>
      </Section>

      <Section id="hipaa" title="HIPAA &amp; Data Handling">
        <p>
          This application logs certain usage activity (searches, form drafts, document generations) for audit and quality purposes. Access to stored data is restricted by user role, and administrative access is limited to designated ProEd staff.
        </p>
        <p>
          Questions about data handling, retention, or access should be directed to ProEd&apos;s compliance team.
        </p>
      </Section>

      <p className="text-xs text-slate-400 italic">
        This page is a working compliance reference and does not constitute legal advice. ProEd&apos;s compliance and legal counsel should review this content periodically and before making it available outside of ProEd&apos;s own staff.
      </p>
    </div>
  );
}
